tasks:
  - name: Install dependecies
    before: sudo apt-get install xorriso axel squashfs-tools -y 1> /dev/null
    init: wget -q "http://mirrors.kernel.org/ubuntu/pool/main/c/cd-boot-images-amd64/cd-boot-images-amd64_20_all.deb" && sudo dpkg -i "cd-boot-images-amd64_20_all.deb" && rm -f "./cd-boot-images-amd64_20_all.deb"