name: Make_Release
on: workflow_dispatch

jobs:
  build:
    name: Build OS
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Build
        env:
             KEY: ${{ secrets.GPG_PRIVATE_KEY }}
             PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
         sudo rm -rf /usr/local/lib/android
         sudo rm -rf /usr/share/dotnet
         sudo rm -rf /opt/ghc
         sudo rm -rf "/usr/local/share/boost"
         sudo rm -rf "$AGENT_TOOLSDIRECTORY"
         sudo apt-get install xorriso coreutils squashfs-tools git axel sed -y
         wget -nv "http://mirrors.kernel.org/ubuntu/pool/main/c/cd-boot-images-amd64/cd-boot-images-amd64_17_all.deb"
         sudo dpkg -i "cd-boot-images-amd64_17_all.deb"
         rm -rf "./cd-boot-images-amd64_17_all.deb"
         cd ~/
         sudo git clone -b $GITHUB_REF_NAME "https://github.com/rollingrhinoremix/RRR-builder.git" && cd ./RRR-builder
         sudo chmod +x ./fetch_build ./build/build.sh ./build/switch.sh ./build/minimal.sh
         sudo ./fetch_build
         sudo rm -rf ./ubuntu.iso
         echo "$KEY" | sudo tee ~/RRR-builder/private.pgp > /dev/null
         echo "$PASSPHRASE" | sudo gpg --batch --allow-secret-key-import --import ~/RRR-builder/private.pgp
         source ~/RRR-builder/build.conf && sudo gpg -o ~/RRR-builder/"$OUT_ISO".sig -u 945D30DAB6C43922 -ab ~/RRR-builder/"$OUT_ISO"
         sudo find . -maxdepth 1 ! \( -name "*.iso*" -o -name '.' -o -name '..' \) -exec sudo rm -rf {} \;
      - uses: actions/upload-artifact@v3.0.0
        with:
          name: "rolling-rhino"
          path: ~/RRR-builder/
          retention-days: 5
          if-no-files-found: error
